model:
  hidden_dim: 256
  num_layers: 8
  num_charts: 8
  c_pe_degree: 1
  t_pe_degree: 4
  s_pe_degree: 4
train:
  mesh_path: data/nefertiti.obj
  epochs: 1
  iters: 10000
  G_num: 10000
  T_num: 10000
loss:
  three_two_three: 1
  two_three_two: 1
  entropy: 0.04
  surface: 10
  cluster: 0.5
  conformal: 0.4
  stretch: 0.1
  texture: 1
optimizer:
  nuvo_lr: 1e-4
  sigma_lr: 0.1
  normal_grids_lr: 0.04
  rgb_grids_lr: 0.04